<script src="js/rtian.js" ></script>
<meta charset="utf-8" />
<title>分类: <span>Version 3.1</span> | jQuery API中文文档(适用jQuery 1.0 - jQuery 3.0)</title>
<div id="content">	
    <div class="inner listing" role="main">
		<header class="page-header">
			<h1 class="page-title">分类: 版本 3.1</h1>
			<hr>
			<div class="category-archive-meta"><p>
<a href="jQuery.readyException.htm" >jQuery.readyException</a> was added.</p>
<hr>
</div>		</header><article id="post-4250" class="post-4250 post type-post status-publish format-standard hentry category-core category-96">
	<header class="entry-header">
		<div class="entry-meta">
			<span class="category">
<a href="core.htm" >核心</a></span>		</div>
					<h1 class="entry-title">
<a href="jQuery.readyException.htm"  title="Permalink to jQuery.readyException()" rel="bookmark">jQuery.readyException()</a>
			</h1>
			</header>
		<div class="entry-summary">
		<p>处理包裹在jQuery()中函数同步抛出的错误。</p>
	</div><!-- .entry-summary -->
</article>
		</div>
  </div>
